### PR TITLE
Fix install directive with 'node-gyp configure build'

### PR DESCRIPTION
**Pull request by rmedaer**
Here the small fix discussed in ffde830278bdfc2f353f79fcd0a2058cecd54ec7 which works for me.
I think it's not an issue for npm packaging.. So it should work !

### CODE REVIEW

**Comment by wankdanker** [comment]
Pushed v1.1.5 to npm.

Thank you, @rmedaer

**Comment by rmedaer** [comment]
You are welcome. It seems to have an other issue with npm and binding. I'll look at this as soon as possible !

Best regards,

**Comment by wankdanker** [comment]
I have no idea what issue you are having now, but the other user who was having a similar issue as originally reported said that they fixed it using `brew install mdbtools`. Not sure if this is helpful in your case.

**Comment by wankdanker** [comment]
And now that I look at mdbtools, I'm definitely guessing that is not your case. :)

**Pull request merged**
